version: "3.8"

services:
  accommodation_reserve_service:
    image: accommodation_reserve_service
    container_name: accommodation_reserve_service
    build:
      context: .
      dockerfile: ./accommodation_reserve_service/Dockerfile
    restart: on-failure
    environment:
      ACCOMMODATION_RESERVE_DB_HOST: ${ACCOMMODATION_RESERVE_DB_HOST}
      ACCOMMODATION_RESERVE_DB_PORT: ${ACCOMMODATION_RESERVE_DB_PORT}
      ACCOMMODATION_RESERVE_SERVICE_PORT: 8000
    depends_on:
      - accommodation_reserve_db
    networks:
      - network


  accommodation_service:
    image: accommodation_service
    container_name: accommodation_service
    build:
      context: .
      dockerfile: ./accommodation_service/Dockerfile
    restart: on-failure
    environment:
      ACCOMMODATION_DB_HOST: ${ACCOMMODATION_DB_HOST}
      ACCOMMODATION_DB_PORT: ${ACCOMMODATION_DB_PORT}
      ACCOMMODATION_SERVICE_PORT: ${ACCOMMODATION_SERVICE_PORT}
    depends_on:
      - accommodation_db
    networks:
      - network

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      ACCOMMODATION_RESERVE_SERVICE_HOST: ${ACCOMMODATION_RESERVE_SERVICE_HOST}
      ACCOMMODATION_RESERVE_SERVICE_PORT: ${ACCOMMODATION_RESERVE_SERVICE_PORT}
      ACCOMMODATION_SERVICE_HOST: ${ACCOMMODATION_SERVICE_HOST}
      ACCOMMODATION_SERVICE_PORT: ${ACCOMMODATION_SERVICE_PORT}

    networks:
      - network

  accommodation_reserve_db:
    image: mongo
    container_name: accommodation_reserve_db
    restart: on-failure
    networks:
      - network


  accommodation_db:
    image: mongo
    container_name: accommodation_db
    restart: on-failure
    networks:
      - network

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_SERVER: accommodation_reserve_db
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - 8081:8081
    networks:
      - network


networks:
  network:
    driver: bridge
