version: "3.8"

services:
  accommodation_reserve_service:
    image: accommodation_reserve_service
    container_name: accommodation_reserve_service
    build:
      context: .
      dockerfile: ./accommodation_reserve_service/Dockerfile
    restart: on-failure
    environment:
      ACCOMMODATION_RESERVE_DB_HOST: ${ACCOMMODATION_RESERVE_DB_HOST}
      ACCOMMODATION_RESERVE_DB_PORT: ${ACCOMMODATION_RESERVE_DB_PORT}
      ACCOMMODATION_RESERVE_SERVICE_PORT: ${ACCOMMODATION_RESERVE_SERVICE_PORT}
    depends_on:
      - accommodation_reserve_db
    networks:
      - network

  user_info_service:
    image: user_info_service
    container_name: user_info_service
    build:
      context: .
      dockerfile: ./user_info_service/Dockerfile
    restart: on-failure
    environment:
      ACCOMMODATION_RESERVE_DB_HOST: ${USER_INFO_DB_HOST}
      ACCOMMODATION_RESERVE_DB_PORT: ${USER_INFO_DB_PORT}
      ACCOMMODATION_RESERVE_SERVICE_PORT: ${USER_INFO_SERVICE_PORT}
    depends_on:
      - user_info_db
    networks:
      - network

  auth_service:
    image: auth_service
    container_name: auth_service
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    restart: on-failure
    environment:
      ACCOMMODATION_RESERVE_DB_HOST: ${AUTH_DB_HOST}
      ACCOMMODATION_RESERVE_DB_PORT: ${AUTH_DB_PORT}
      ACCOMMODATION_RESERVE_SERVICE_PORT: ${AUTH_SERVICE_PORT}
    depends_on:
      - auth_db
    networks:
      - network

  accommodation_service:
    image: accommodation_service
    container_name: accommodation_service
    build:
      context: .
      dockerfile: ./accommodation_service/Dockerfile
    restart: on-failure
    environment:
      ACCOMMODATION_RESERVE_DB_HOST: ${ACCOMMODATION_DB_HOST}
      ACCOMMODATION_RESERVE_DB_PORT: ${ACCOMMODATION_DB_PORT}
      ACCOMMODATION_RESERVE_SERVICE_PORT: ${ACCOMMODATION_SERVICE_PORT}
    depends_on:
      - accommodation_db
    networks:
      - network

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      ACCOMMODATION_RESERVE_SERVICE_HOST: ${ACCOMMODATION_RESERVE_SERVICE_HOST}
      ACCOMMODATION_RESERVE_SERVICE_PORT: ${ACCOMMODATION_RESERVE_SERVICE_PORT}
    networks:
      - network

  accommodation_reserve_db:
    image: mongo
    container_name: accommodation_reserve_db
    restart: on-failure
    networks:
      - network
    ports:
      - 4000:27017
    environment:
      - MONGO_INITDB_DATABASE=xws
    volumes:
      - accommodation_reserve_db-data:/data/db

  user_info_db:
    image: mongo
    container_name: user_info_db
    restart: on-failure
    networks:
      - network
    ports:
      - 4003:27017
    environment:
      - MONGO_INITDB_DATABASE=xws
    volumes:
      - user_info_db-data:/data/db

  auth_db:
    image: mongo
    container_name: auth_db
    restart: on-failure
    networks:
      - network
    ports:
      - 4002:27017
    environment:
      - MONGO_INITDB_DATABASE=xws
    volumes:
      - auth_db-data:/data/db

  accommodation_db:
    image: mongo
    container_name: accommodation_db
    restart: on-failure
    networks:
      - network
    ports:
      - 4001:27017
    environment:
      - MONGO_INITDB_DATABASE=xws
    volumes:
      - accommodation_db-data:/data/db


  mongo-express:
      image: mongo-express
      container_name: accommodation-booking-webapp-mongo-express
      restart: always
      networks:
        - network
      ports:
        - 8081:8081
      environment:
        - ME_CONFIG_MONGODB_SERVER= accommodation_reserve_db
        - ME_CONFIG_MONGODB_SERVER= accommodation_db
        - ME_CONFIG_MONGODB_SERVER= user_info_db
        - ME_CONFIG_MONGODB_SERVER= auth_db

volumes:
  accommodation_reserve_db-data:
    name: server-database
  accommodation_db-data:
    name: server-database
  user_info_db-data:
    name: server-database
  auth_db-data:
    name: server-database


networks:
  network:
    driver: bridge