// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: accommodation_reserve_service.proto

package accommodation_reserve

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccommodationReserveService_Get_FullMethodName = "/catalogue.accommodation_reserve_service/Get"
)

// AccommodationReserveServiceClient is the client API for AccommodationReserveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccommodationReserveServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type accommodationReserveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccommodationReserveServiceClient(cc grpc.ClientConnInterface) AccommodationReserveServiceClient {
	return &accommodationReserveServiceClient{cc}
}

func (c *accommodationReserveServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, AccommodationReserveService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccommodationReserveServiceServer is the server API for AccommodationReserveService service.
// All implementations must embed UnimplementedAccommodationReserveServiceServer
// for forward compatibility
type AccommodationReserveServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedAccommodationReserveServiceServer()
}

// UnimplementedAccommodationReserveServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccommodationReserveServiceServer struct {
}

func (UnimplementedAccommodationReserveServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAccommodationReserveServiceServer) mustEmbedUnimplementedAccommodationReserveServiceServer() {
}

// UnsafeAccommodationReserveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccommodationReserveServiceServer will
// result in compilation errors.
type UnsafeAccommodationReserveServiceServer interface {
	mustEmbedUnimplementedAccommodationReserveServiceServer()
}

func RegisterAccommodationReserveServiceServer(s grpc.ServiceRegistrar, srv AccommodationReserveServiceServer) {
	s.RegisterService(&AccommodationReserveService_ServiceDesc, srv)
}

func _AccommodationReserveService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccommodationReserveServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccommodationReserveService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccommodationReserveServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccommodationReserveService_ServiceDesc is the grpc.ServiceDesc for AccommodationReserveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccommodationReserveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogue.accommodation_reserve_service",
	HandlerType: (*AccommodationReserveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _AccommodationReserveService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accommodation_reserve_service.proto",
}
